spring:
  security:
    oauth2:
      client:
        registration:
          naver:
#            client-name: google
            client-id: VBDN7BLg_tBHITldn6MH
            client-secret: gIWyjp28kZ
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/ouath2/code/naver"
            scope:
             - nickname
             - email
             - profile_image
            clientName: Naver
        provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
                  # 기준이 되는 user_name 의 이름을 네이버에서는 response로 지정해야한다. (네이버 회원 조회시 반환되는 JSON 형태 떄문이다)
              user-name-attribute: response
app:
  auth:
    tokenSecret: TOKEN_SECRET
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8083/oauth/redirect


#cors:
#  allowed-origins: 'http://localhost:8083'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600
#              - email
#              - profile
